//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prepare_1_2_MVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> CategoryFK { get; set; }
        [Required]
        [Range(1, 150, ErrorMessage = "The age must be between 1 and 150.")]
        public Nullable<int> Stock { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
