//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prepare_13_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Courses
    {
        public int FK_Student { get; set; }
        public int Fk_Course { get; set; }
        public string note { get; set; }
        public int id { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Student Student { get; set; }
    }
}
