//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_13_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Major
    {
        public int Id { get; set; }
        public string Name_Major { get; set; }
        public string Description_Major { get; set; }
        public int Fk_Major { get; set; }
        public string image { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
